### ISSUE TITLE
Pass Mozilla Observatory test with a respectable grade

### ISSUE THREAD

**Issue by stigok** [hackeriet/hackeriet.no#10]
https://observatory.mozilla.org/analyze.html?host=hackeriet.no

> Observatory by Mozilla is a project designed to help developers, system administrators, and security professionals configure their sites safely and securely.

**TODO**
- [x] Content Security Policy (CSP) header not implemented
- [x] Does not redirect to an https site
- [x] X-Content-Type-Options header not implemented
- [x] X-XSS-Protection header not implemented

**Comment by stigtsp** [comment]
A+
